on: [push]

name: Run cargo test

jobs:
  build_and_test:
    name: libnetplan-rs
    runs-on: ubuntu-latest
    container:
      image: ubuntu:noble
    steps:
      - uses: actions/checkout@v2
      - run: apt update && apt -y install libnetplan-dev curl wget build-essential libclang1 libclang-dev
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release -- --test-threads=1
